import {useEffect,useState} from 'react';
import {Activity,CheckCircle2,RefreshCw,Settings2,WifiOff,Zap} from 'lucide-react';
import {analyzeJobs,health,importJobs,login,profile as getProfile,register,stats,updateProfile} from '../shared/api';
import type {Analysis,ExtractedJob} from '../shared/types';
import {clearSession,defaults,getSession,getSettings,requestBackendAccess,saveSession,Settings} from '../shared/storage';

type Health={ok:boolean;groq_configured:boolean};
type Stats={jobs:number;analyzed:number;strong_matches:number;review:number;skipped:number;prepared:number;applied:number};
type Candidate={personal?:{location?:string};professional?:{current_title?:string;total_experience_years?:number|null};skills?:string[];[key:string]:unknown};
type PageScan={url:string;anchorCount:number;jobs:ExtractedJob[]};
type Decoration={jobUrl:string;analysis?:Analysis;status:string;reason?:string};

export function scanNaukriPage():PageScan{
  const anchors=Array.from(document.querySelectorAll<HTMLAnchorElement>('a[href]'));
  const isJobLink=(anchor:HTMLAnchorElement)=>{try{const url=new URL(anchor.href,location.href);return /job-listings|\/job\//i.test(url.pathname)||url.searchParams.has('jobId')}catch{return false}};
  const links=anchors.filter(anchor=>isJobLink(anchor)&&Boolean(anchor.textContent?.trim())&&!/^(apply|save|view)$/i.test(anchor.textContent?.trim()||''));
  const unique=new Map<string,HTMLAnchorElement>();
  for(const link of links){const url=link.href.split('#')[0];if(!unique.has(url))unique.set(url,link)}
  const jobs:Array<ExtractedJob>=[];
  for(const [jobUrl,link] of unique){
    let card:Element=link;let node=link.parentElement;
    for(let depth=0;node&&depth<8;depth++,node=node.parentElement){const count=Array.from(node.querySelectorAll<HTMLAnchorElement>('a[href]')).filter(isJobLink).length;const length=(node.textContent||'').trim().length;if(count>1)break;if(length>(link.textContent||'').trim().length+8&&length<5000)card=node}
    const pick=(selectors:string)=>card.querySelector(selectors)?.textContent?.replace(/\s+/g,' ').trim()||undefined;
    const title=link.textContent?.replace(/\s+/g,' ').trim();if(!title)continue;
    const parsed=new URL(jobUrl,location.href);
    jobs.push({externalId:card.getAttribute('data-job-id')||parsed.searchParams.get('jobId')||parsed.pathname.match(/(\d{5,})/)?.[1],title,company:pick('.comp-name,[class*="comp-name" i],[class*="company-name" i],[class*="company" i]')||'Unknown company',location:pick('.locWdth,.location,[class*="location" i],[class*="loc-" i]'),experienceText:pick('.expwdth,.experience,[class*="experience" i],[class*="exp-" i]'),salary:pick('.salary,[class*="salary" i],[class*="sal-" i]'),skills:(pick('.tags-gt,.skill-tags,[class*="skill" i]')||'').split(/•|,/).map(value=>value.trim()).filter(Boolean).slice(0,15),postedText:pick('.job-post-day,.freshness,[class*="posted" i]'),description:pick('.job-desc,.job-description,[class*="description" i]'),jobUrl});
  }
  return {url:location.href,anchorCount:anchors.length,jobs};
}

export function decorateNaukriPage(decorations:Decoration[]){
  for(const item of decorations){const link=Array.from(document.querySelectorAll<HTMLAnchorElement>('a[href]')).find(anchor=>anchor.href.split('#')[0]===item.jobUrl);if(!link)continue;let card:Element=link;let node=link.parentElement;for(let depth=0;node&&depth<8;depth++,node=node.parentElement){const length=(node.textContent||'').trim().length;if(length>link.textContent!.trim().length+8&&length<5000)card=node}let badge=Array.from(card.querySelectorAll<HTMLElement>('[data-naukri-ai-direct]')).find(element=>element.dataset.naukriAiDirect===item.jobUrl);if(!badge){badge=document.createElement('div');badge.dataset.naukriAi='true';badge.dataset.naukriAiDirect=item.jobUrl;badge.style.cssText='margin:8px 0;padding:8px 11px;border-radius:8px;font:700 13px system-ui;position:relative;z-index:3';card.prepend(badge)}if(item.analysis){badge.textContent=`${item.analysis.match_score}% ${item.analysis.recommendation.replace('_',' ')}`;badge.style.background=item.analysis.recommendation==='STRONG_MATCH'?'#e3fcef':item.analysis.recommendation==='REVIEW'?'#fff4ce':'#f2f4f7';badge.style.color=item.analysis.recommendation==='STRONG_MATCH'?'#087f5b':item.analysis.recommendation==='REVIEW'?'#9a6700':'#667085'}else{badge.textContent=`SKIPPED — ${item.reason||'rule filter'}`;badge.style.background='#f2f4f7';badge.style.color='#667085'}}
  return decorations.length;
}

function App(){
  const [state,setState]=useState<Health|null>(null); const [summary,setSummary]=useState<Stats|null>(null);
  const [settings,setSettings]=useState<Settings>(defaults); const [error,setError]=useState(''); const [scanning,setScanning]=useState(false);
  const [account,setAccount]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [authBusy,setAuthBusy]=useState(false);
  const [candidate,setCandidate]=useState<Candidate>({personal:{location:''},professional:{current_title:'',total_experience_years:0},skills:[]});
  const check=()=>Promise.all([health(),stats(),getProfile()]).then(([h,s,p])=>{const candidateProfile=p as Candidate;setState(h);setSummary(s);setCandidate({...candidateProfile,professional:{...candidateProfile.professional,total_experience_years:candidateProfile.professional?.total_experience_years??0}});setError('')}).catch(e=>{setState(null);setError(e.message||'Backend unavailable')});
  useEffect(()=>{getSettings().then(setSettings);getSession().then(session=>{if(session.account?.email){setAccount(session.account.email);check()}else health().then(setState).catch(()=>setState(null))})},[]);
  const authenticate=async(create=false)=>{setAuthBusy(true);try{const result=create?await register(email,password):await login(email,password);await saveSession(result.token,{email:result.user.email});setAccount(result.user.email);setPassword('');setError(create?'Account created. Complete your profile below.':'Signed in');check()}catch(e){setError(e instanceof Error?e.message:'Unable to sign in')}finally{setAuthBusy(false)}};
  const signOut=async()=>{await clearSession();setAccount('');setSummary(null);setCandidate({personal:{location:''},professional:{current_title:'',total_experience_years:0},skills:[]});setError('Signed out from this browser')};
  const save=async()=>{try{if(!await requestBackendAccess(settings.backendUrl))throw new Error('Permission is needed to connect to that backend');await chrome.storage.sync.set(settings);setError('Settings saved')}catch(e){setError(e instanceof Error?e.message:'Unable to save settings')}};
  const saveProfile=async()=>{await updateProfile(candidate);setError('Candidate profile saved')};
  const analyzeAgain=async()=>{const started=Date.now();setScanning(true);try{const tabs=await chrome.tabs.query({active:true,currentWindow:true});const tab=tabs[0];if(!tab?.id||!tab.url?.includes('naukri.com'))throw new Error('Open a Naukri tab first');const execution=await chrome.scripting.executeScript({target:{tabId:tab.id},func:scanNaukriPage});const page=execution[0]?.result as PageScan|undefined;if(!page)throw new Error('Chrome did not return page data');if(!page.jobs.length){setError(`Found 0 job links among ${page.anchorCount} links on ${new URL(page.url).pathname}`);return}const imported=await importJobs(page.jobs);const pending=imported.filter(item=>item.status==='ANALYSIS_PENDING').map(item=>item.id);const analyzed=pending.length?await analyzeJobs(pending):[];const decorations:Decoration[]=imported.map((item,index)=>({jobUrl:page.jobs[index].jobUrl,analysis:item.analysis||analyzed.find(result=>result.id===item.id)?.analysis,status:item.status,reason:item.filter_reason||analyzed.find(result=>result.id===item.id)?.error}));await chrome.scripting.executeScript({target:{tabId:tab.id},func:decorateNaukriPage,args:[decorations]});setError(`Analyzed ${decorations.length} visible jobs. Badges added to Naukri.`);const latest=await stats();setSummary(latest)}catch(error){setError(error instanceof Error?error.message:'Unable to analyze this Naukri page')}finally{const remaining=1000-(Date.now()-started);if(remaining>0)await new Promise<void>(resolve=>window.setTimeout(resolve,remaining));setScanning(false)}};
  return <main>
    <header><div className="logo"><Zap size={18}/></div><div><h1>Naukri AI Assistant</h1><p>Private intelligence layer</p></div></header>
    <section className="status">{state?<><CheckCircle2 className="good" size={18}/><div><b>Backend connected</b><small>Groq {state.groq_configured?'ready':'not configured'}</small></div></>:<><WifiOff className="bad" size={18}/><div><b>Backend offline</b><small>{error||'Start FastAPI on localhost:8001'}</small></div></>}</section>
    {!account?<section className="section"><div className="section-title"><Settings2 size={16}/>Your Naukri AI account</div><p className="muted">Create an account to keep your profile and matches private to you.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} /></label><label>Password<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} /></label><button disabled={authBusy} onClick={()=>authenticate(false)}>Sign in</button><button className="primary" disabled={authBusy} onClick={()=>authenticate(true)}>Create account</button></section>:<section className="section"><div className="section-title"><CheckCircle2 size={16}/>Signed in</div><p className="muted">{account}. Your profile and results are private to this account.</p><button onClick={signOut}>Sign out</button></section>}
    {account&&<>
    <section className="section"><div className="section-title"><Activity size={16}/>Current page</div><p className="muted">Open a normal Naukri search page. Rendered cards are detected automatically.</p><button className="primary" disabled={scanning} onClick={analyzeAgain}><RefreshCw size={15}/>{scanning?'Analyzing…':'Analyze visible jobs'}</button></section>
    {error&&<p className="notice">{error}</p>}{summary&&<section className="metrics">{[['jobs','Detected'],['strong_matches','Strong'],['review','Review'],['skipped','Skipped'],['applied','Applied today']].map(([key,label])=><div className="metric" key={key}><strong>{summary[key as keyof Stats]}</strong><span>{label}</span></div>)}</section>}
    <section className="section"><div className="section-title"><Settings2 size={16}/>Candidate profile</div>{!candidate.skills?.length&&<p className="notice">Add verified profile facts before analyzing jobs. Empty profiles produce low scores.</p>}<label>Current title<input value={candidate.professional?.current_title||''} onChange={e=>setCandidate({...candidate,professional:{...candidate.professional,current_title:e.target.value}})}/></label><label>Total experience in years<input type="number" min="0" step="0.5" value={candidate.professional?.total_experience_years??''} onChange={e=>setCandidate({...candidate,professional:{...candidate.professional,total_experience_years:e.target.value===''?null:Number(e.target.value)}})}/></label><label>Current location<input value={candidate.personal?.location||''} onChange={e=>setCandidate({...candidate,personal:{...candidate.personal,location:e.target.value}})}/></label><label>Skills, comma separated<textarea value={(candidate.skills||[]).join(', ')} onChange={e=>setCandidate({...candidate,skills:e.target.value.split(',').map(skill=>skill.trim()).filter(Boolean)})}/></label><button className="primary" onClick={saveProfile}>Save profile</button></section>
    <section className="section"><div className="section-title"><Settings2 size={16}/>Settings</div><label>Backend URL<input value={settings.backendUrl} onChange={e=>setSettings({...settings,backendUrl:e.target.value})}/></label><label className="toggle"><input type="checkbox" checked={settings.autoAnalyze} onChange={e=>setSettings({...settings,autoAnalyze:e.target.checked})}/> Auto analyze visible jobs</label><label className="toggle"><input type="checkbox" checked={settings.autoFill} onChange={e=>setSettings({...settings,autoFill:e.target.checked})}/> Auto-fill verified fields only</label><label>Strong match threshold<input type="number" min="0" max="100" value={settings.strongMatch} onChange={e=>setSettings({...settings,strongMatch:+e.target.value})}/></label><label className="toggle"><input type="checkbox" checked={settings.debug} onChange={e=>setSettings({...settings,debug:e.target.checked})}/> Debug mode</label><button onClick={check}><RefreshCw size={15}/>Check connection</button><button className="primary" onClick={save}>Save settings</button></section>
    </>}<footer>Final Naukri submission always stays under your control.</footer>
  </main>
}
export default App;
