from datetime import datetime,timezone
from sqlalchemy import DateTime,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from .db import Base
def now():return datetime.now(timezone.utc)
class Job(Base):
    __tablename__='jobs';id:Mapped[int]=mapped_column(primary_key=True);user_id:Mapped[int|None]=mapped_column(Integer,index=True,nullable=True);naukri_context:Mapped[str]=mapped_column(String(64),index=True,default='default');identity:Mapped[str]=mapped_column(String(64),unique=True,index=True);external_id:Mapped[str|None]=mapped_column(String(200),nullable=True);title:Mapped[str]=mapped_column(String(300));company:Mapped[str]=mapped_column(String(300));location:Mapped[str|None]=mapped_column(String(300),nullable=True);experience_text:Mapped[str|None]=mapped_column(String(200),nullable=True);salary:Mapped[str|None]=mapped_column(String(200),nullable=True);skills:Mapped[list]=mapped_column(JSON,default=list);posted_text:Mapped[str|None]=mapped_column(String(100),nullable=True);job_url:Mapped[str]=mapped_column(String(1000));description:Mapped[str|None]=mapped_column(Text,nullable=True);source:Mapped[str]=mapped_column(String(50),default='naukri_page');first_seen_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);last_seen_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);match_score:Mapped[int|None]=mapped_column(Integer,nullable=True);recommendation:Mapped[str|None]=mapped_column(String(30),nullable=True);status:Mapped[str]=mapped_column(String(30),default='DISCOVERED');analysis:Mapped[dict]=mapped_column(JSON,default=dict)
class Analysis(Base):
    __tablename__='analyses';id:Mapped[int]=mapped_column(primary_key=True);user_id:Mapped[int|None]=mapped_column(Integer,index=True,nullable=True);job_id:Mapped[int]=mapped_column(index=True);model:Mapped[str]=mapped_column(String(100));analysis_json:Mapped[dict]=mapped_column(JSON);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Application(Base):
    __tablename__='applications';id:Mapped[int]=mapped_column(primary_key=True);user_id:Mapped[int|None]=mapped_column(Integer,index=True,nullable=True);job_id:Mapped[int]=mapped_column(index=True);status:Mapped[str]=mapped_column(String(30),default='PREPARED');prepared_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);applied_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True);notes:Mapped[str|None]=mapped_column(Text,nullable=True)
class User(Base):
    __tablename__='users';id:Mapped[int]=mapped_column(primary_key=True);email:Mapped[str]=mapped_column(String(320),unique=True,index=True);password_hash:Mapped[str]=mapped_column(String(256));profile:Mapped[dict]=mapped_column(JSON,default=dict);preferences:Mapped[dict]=mapped_column(JSON,default=dict);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class AccessToken(Base):
    __tablename__='access_tokens';id:Mapped[int]=mapped_column(primary_key=True);user_id:Mapped[int]=mapped_column(Integer,index=True);token_hash:Mapped[str]=mapped_column(String(64),unique=True,index=True);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class PasswordResetToken(Base):
    __tablename__='password_reset_tokens';id:Mapped[int]=mapped_column(primary_key=True);user_id:Mapped[int]=mapped_column(Integer,index=True);token_hash:Mapped[str]=mapped_column(String(64),unique=True,index=True);expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True);used_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ProfileContext(Base):
    __tablename__='profile_contexts';__table_args__=(UniqueConstraint('user_id','context_key'),);id:Mapped[int]=mapped_column(primary_key=True);user_id:Mapped[int]=mapped_column(Integer,index=True);context_key:Mapped[str]=mapped_column(String(64),index=True);profile:Mapped[dict]=mapped_column(JSON,default=dict);preferences:Mapped[dict]=mapped_column(JSON,default=dict);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
